# Makefile
TARGET	= user_test
CC=$(CROSS_COMPILE)gcc
NVCC	= nvcc -arch sm_20 -cubin
LIBS	= -L/home/armcca/trusted-peripherals/assets/snapshots/aarch64-lib -lucuda -lgdev
CFLAGS	= -I/usr/local/gdev/include

all: nvcc gcc

nvcc:
	$(NVCC) -o madd_gpu.cubin madd_gpu.cu

gcc:
	$(CC) -o $(TARGET) $(CFLAGS) main.c madd_host.c $(LIBS)

clean:
	rm -f $(TARGET) *.cubin ./*~
