#!/bin/sh
set +x

if [ -z "$DATA_DIR" ]
then
    export DATA_DIR=../../data
fi

arg=512
echo "hotspot-$arg" > /mnt/host/fvp-trace || true

nice -20 ./hotspot $arg 2 10 ${DATA_DIR}/hotspot/temp_512 ${DATA_DIR}/hotspot/power_512 output.out
